# Generated by Django 3.0.6 on 2020-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_data', '0002_auto_20200623_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_store',
            name='value',
        ),
        migrations.AddField(
            model_name='data_store',
            name='amplitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data_store',
            name='time',
            field=models.FloatField(null=True),
        ),
    ]
